=== api-evangelist/amazon-mediapackage/json-schema/mediapackage-api-create-origin-endpoint-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-mediapackage/refs/heads/main/json-schema/mediapackage-api-create-origin-endpoint-request-schema.json",
  "title": "CreateOriginEndpointRequest",
  "description": "Configuration parameters used to create a new OriginEndpoint.",
  "type": "object",
  "properties": {
    "Authorization": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Authorization"
        },
        {
          "xml": {
            "name": "authorization"
          }
        }
      ]
    },
    "ChannelId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "channelId"
          },
          "description": "The ID of the Channel that the OriginEndpoint will be associated with.\nThis cannot be changed after the OriginEndpoint is created.\n"
        }
      ]
    },
    "CmafPackage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CmafPackageCreateOrUpdateParameters"
        },
        {
          "xml": {
            "name": "cmafPackage"
          }
        }
      ]
    },
    "DashPackage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DashPackage"
        },
        {
          "xml": {
            "name": "dashPackage"
          }
        }
      ]
    },
    "Description": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "description"
          },
          "description": "A short text description of the OriginEndpoint."
        }
      ]
    },
    "HlsPackage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HlsPackage"
        },
        {
          "xml": {
            "name": "hlsPackage"
          }
        }
      ]
    },
    "Id": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "id"
          },
          "description": "The ID of the OriginEndpoint.  The ID must be unique within the region\nand it cannot be changed after the OriginEndpoint is created.\n"
        }
      ]
    },
    "ManifestName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "manifestName"
          },
          "description": "A short string that will be used as the filename of the OriginEndpoint URL (defaults to \"index\")."
        }
      ]
    },
    "MssPackage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/MssPackage"
        },
        {
          "xml": {
            "name": "mssPackage"
          }
        }
      ]
    },
    "Origination": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Origination"
        },
        {
          "xml": {
            "name": "origination"
          },
          "description": "Control whether origination of video is allowed for this OriginEndpoint. If set to ALLOW, the OriginEndpoint\nmay by requested, pursuant to any other form of access control. If set to DENY, the OriginEndpoint may not be\nrequested. This can be helpful for Live to VOD harvesting, or for temporarily disabling origination\n"
        }
      ]
    },
    "StartoverWindowSeconds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__integer"
        },
        {
          "xml": {
            "name": "startoverWindowSeconds"
          },
          "description": "Maximum duration (seconds) of content to retain for startover playback.\nIf not specified, startover playback will be disabled for the OriginEndpoint.\n"
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Tags"
        },
        {
          "xml": {
            "name": "tags"
          }
        }
      ]
    },
    "TimeDelaySeconds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__integer"
        },
        {
          "xml": {
            "name": "timeDelaySeconds"
          },
          "description": "Amount of delay (seconds) to enforce on the playback of live content.\nIf not specified, there will be no time delay in effect for the OriginEndpoint.\n"
        }
      ]
    },
    "Whitelist": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__listOf__string"
        },
        {
          "xml": {
            "name": "whitelist"
          },
          "description": "A list of source IP CIDR blocks that will be allowed to access the OriginEndpoint."
        }
      ]
    }
  },
  "required": [
    "ChannelId",
    "Id"
  ]
}

=== api-evangelist/amazon-mediapackage/examples/mediapackage-api-create-origin-endpoint-request-example.json
{
  "Authorization": "example-value",
  "ChannelId": "id-abc123",
  "CmafPackage": "example-value",
  "DashPackage": "example-value",
  "Description": "example-value",
  "HlsPackage": "example-value",
  "Id": "id-abc123",
  "ManifestName": "example-resource",
  "MssPackage": "example-value",
  "Origination": "example-value",
  "StartoverWindowSeconds": "example-value",
  "Tags": "example-value",
  "TimeDelaySeconds": "example-value",
  "Whitelist": "example-value"
}
